### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by slstenton**
scripts to generate tables for Sanna's study

### CODE REVIEW

**Review by jkgoodrich — COMMENTED** [review]
This looks great, thanks for adding. Just one thought (not only for you, I should have done it for my script too), maybe add a README.md to this directory and for each script put the one line description of what it does, and the manuscript it was used for.

**Comment by slstenton** [comment]
Thanks Julia! Just added the README.md

**Review by jkgoodrich — APPROVED** [review]
LGTM!

**Comment by slstenton** [comment]
Nice, I don't have permission to merge, could you do it?

**Pull request merged**
